-- Migration to change cover_letter column from VARCHAR(2000) to TEXT
-- This allows storing longer cover letters generated by AI

ALTER TABLE job_applications 
ALTER COLUMN cover_letter TYPE TEXT;


